spring:

  config:
    import: optional:file:../.env[.properties]  

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Sao_Paulo

  application:
    name: wallet-core

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://wallet-pg16:5432/db_wallet
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
