spring:
  application:
    name: gateway

  config:
    import:
      - optional:file:../.env[.properties]

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        - id: wallet-core
          uri: http://localhost:8080
          predicates:
            - Path=/wallet/**
          filters:
            - StripPrefix=1

        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
            - RemoveRequestHeader=Cookie

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health